apiVersion: v1
kind: Service
metadata:
  name: acquirer-frontend-clusterip-service
spec:
  type: {{ .Values.acquirerFrontend.service.type }}
  selector:
    component: acquirer-frontend
  ports:
    - port: {{ .Values.acquirerFrontend.service.port }}
      targetPort: {{ .Values.acquirerFrontend.service.port }}
