apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-db-init-script
data:
  init-db.sql: |
    {{- range .Values.merchantDb.databases }}
    CREATE DATABASE IF NOT EXISTS {{ .name }};
    {{- end }}

