apiVersion: v1
kind: Service
metadata:
  name: merchant-db-clusterip-service
spec:
  type: {{ .Values.merchantDb.service.type }}
  selector:
    component: merchant-db
  ports:
    - protocol: TCP
      port: {{ .Values.merchantDb.service.port }}
      targetPort: {{ .Values.merchantDb.service.port }}
