apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  selector:
    matchLabels:
      component: minio
  replicas: {{ .Values.minio.replicaCount }}
  template:
    metadata:
      labels:
        component: minio
    spec:
      containers:
        - name: minio
          image: "{{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}"
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.env.rootUser }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.minio.env.rootPassword }}"
          ports:
            - containerPort: {{ .Values.minio.service.port }}
          volumeMounts:
            - name: storage
              mountPath: "/data"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.minio.pvc.name }}
