apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-s3-pvc
spec:
  accessModes:
    - {{ .Values.minio.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.minio.pvc.size }}

