registryOracle:
  replicaCount: 1
  image:
    repository: twstm/registry-oracle
    tag: 0.0.3k
  service:
    type: ClusterIP
    port: 8888
  env:
    dbHost: merchant-db-clusterip-service
    dbPort: "3306"
    database: registry_db
    dbUsername: root
    dbPasswordSecret:
      name: merchant-db-secret
      key: mysql-root-password
    rabbitmqHost: rabbitmq-clusterip-service
    rabbitmqPort: "5672"
    rabbitmqUsername: guest
    rabbitmqPassword: guest

